### ISSUE TITLE
Try out codon PRANK

### ISSUE THREAD

**Issue by matsen** [cswarth/hiv-sim#2]
> For DNA data, PRANK by default uses HKY model with empirical base frequencies and kappa=2. With the optional command parameters, it supports TN (TN93) and models below it (JC, K2P, FEL, HKY). For example, JC model is defined as -kappa=1 -dnafreqs=0.25,0.25,0.25,0.25. WAG (WG01) is used for protein alignments but, so far, the software isn't much tested for that and other programs may do better. For protein coding DNA data, one can also use the empirical codon substitution model (kindly provided by Carolin Kosiol). Translation into codons is done in the first forward frame without any error-checking.

**Comment by cswarth** [comment]
From https://code.google.com/p/prank-msa/wiki/PRANK?tm=6#Methods
> Translation into amino acids and codons is done in the first forward frame without any error-checking.  Based on independent benchmarks, codon alignment produces more accurate alignments than alignment of translated protein sequences.

This seems to imply the codon translation begins at the first position in the aligned sequence.  That means all simulated sequences will have to begin at the start of a coding region.  I don't think this is a problem as I believe we are using HIV-1 pol as a founder of our foward-in-time simulation (I'll double check).  The coding region must remain in-frame (see  issue #8).  The assumption that the founding sequence is protein coding and begins at the start of a coding region will make implementation of Issue #8 significantly easier.
