### ISSUE TITLE
Codons and simulation

### ISSUE THREAD

**Issue by matsen** [cswarth/hiv-sim#8]
What about only simulating indels of length three? (Or simulating on the level of amino acids?). In that way we would be enforcing a strict no-frame-shifts fitness function, which might be a big savings.

This sort of thing might fit in well with #7, in that we could simulate on the level of codons or amino acids, and then throw in some nucleotide-level nonsense.

**Comment by cswarth** [comment]
The simplest approach is to simply never allow an indel that is not a integral multiple of 3nt long.  Also never allow insertion of a stop codon.  Is preventing the generation of unfit virions statistically the same as culling them in a fitness function?

Just speculating what it would take to implement a more sophisticated approach. 
What is important from a fitness standpoint is that protein coding regions be an integral number of codons long, and that premature stop codons are not introduced.  Strictly speaking, non-integral indels outside of coding regions don't matter, but are there any significant non-coding regions in the HIV genome?  

Coding regions are specified in the SANTA config file as ranges on the founding virus.  There are a couple of problems with simply using these ranges to track the boundaries of a protein coding region as the virus evolves.  The first is that the ranges are implemented as static values; they never change as the virus evolves.  The second issue (not really a problem) is that we must be sure to copy updated range definitions when establishing a simulated transmission founder.  Right now we just copy the founding virus into a new santa config file.  If we are using ranges to define coding boundaries, then they are unique the particular genome and will also have to be copied to make a new founder.  That implies that SANTA needs to report those ranges with each sampled virus.

**Comment by cswarth** [comment]
It seems to be there are two ways to generate indels that fit our requirement that they not change the frame.   

The first would be generate the indels according to a neutral criteria and then filter out those we don't like.  The second would be to generate only valid indels positions and lengths to begin with.  

The former is more like a natural evolutionary process, and rates for various processes from the literature seem to presume a neutral process.  As a first cut, I'm going to generate the events and then filter them.

**Comment by cswarth** [comment]
santa simulation updated
